FROM scratch AS ctx

COPY build/shared/ /shared

FROM docker.io/archlinux/archlinux:latest AS base

FROM base AS builder

RUN pacman -Syu --noconfirm make git rust go-md2man ostree glibc pkgconf

WORKDIR /home/build
RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    /ctx/shared/build.sh

FROM base AS system

COPY --from=builder /output /

RUN grep "= */var" /etc/pacman.conf | sed "/= *\/var/s/.*=// ; s/ //" | xargs -n1 sh -c 'mkdir -p "/usr/lib/sysimage/$(dirname $(echo $1 | sed "s@/var/@@"))" && mv -v "$1" "/usr/lib/sysimage/$(echo "$1" | sed "s@/var/@@")"' '' && \
    sed -i -e "/= *\/var/ s/^#//" -e "s@= */var@= /usr/lib/sysimage@g" -e "/DownloadUser/d" /etc/pacman.conf

RUN pacman -Syu --noconfirm

RUN pacman -Sy --noconfirm base dracut linux linux-firmware ostree btrfs-progs e2fsprogs xfsprogs dosfstools skopeo dbus dbus-glib glib2 ostree shadow && pacman -S --clean --noconfirm

RUN --mount=type=tmpfs,dst=/tmp --mount=type=tmpfs,dst=/root \
    --mount=type=bind,from=ctx,source=/,target=/ctx \
    /ctx/shared/initramfs.sh

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    sed -i 's|^HOME=.*|HOME=/var/home|' "/etc/default/useradd" && \
    /ctx/shared/bootc-rootfs.sh

LABEL containers.bootc 1

RUN bootc container lint
