local wk = require("which-key")

wk.setup({
  preset = "classic",
  plugins = {
    spelling = { enabled = true },
    presets = {
      operators = true,
      motions = true,
      text_objects = true,
      windows = true,
      nav = true,
      z = true,
      g = true,
    },
  },
})

wk.add({
  { "<leader>a", group = "aerial" },
  { "<leader>at", desc = "Toggle outline" },
  { "<leader>b", group = "buffer" },
  { "<tab>", desc = "Next buffer" },
  { "<S-tab>", desc = "Previous buffer" },
  { "<leader>c", group = "code" },
  { "<leader>g", group = "git" },
  { "<leader>gh", group = "hunks" },
  { "<leader>ghs", desc = "Stage hunk", mode = { "n", "v" } },
  { "<leader>ghr", desc = "Reset hunk", mode = { "n", "v" } },
  { "<leader>ghS", desc = "Stage buffer" },
  { "<leader>ghu", desc = "Undo stage hunk" },
  { "<leader>ghR", desc = "Reset buffer" },
  { "<leader>ghp", desc = "Preview hunk" },
  { "<leader>ghb", desc = "Blame line" },
  { "<leader>ghd", desc = "Diff this" },
  { "<leader>ghD", desc = "Diff this ~" },
  { "<leader>ght", desc = "Toggle line blame" },
  { "<leader>ghT", desc = "Toggle deleted" },
  { "<leader>q", group = "session" },
  { "<leader>qs", desc = "Restore session" },
  { "<leader>ql", desc = "Restore last session" },
  { "<leader>qd", desc = "Stop saving session" },
  { "<leader>s", group = "search" },
  { "<leader>k", desc = "Neo-tree" },
  { "<leader>x", desc = "Close buffer" },
  { "<leader>p", desc = "Paste without yanking", mode = "x" },
  { "<leader>y", desc = "Yank to clipboard", mode = { "n", "v" } },
  { "<leader>d", desc = "Delete without yanking", mode = { "n", "v" } },
  { "<leader>?", desc = "Which-key (buffer local)" },
})
