#!/bin/bash
# arrange-outputs.sh — Dynamically position eDP-1 centered below all external monitors.
#
# Writes ~/.config/niri/output-positions.kdl, which is included by config.kdl
# via an optional include. Niri live-reloads when the file changes.
#
# Triggered by spawn-at-startup in config.kdl.
# Can also be run manually after hotplugging a monitor.

set -euo pipefail

CONFIG_DIR="$HOME/.config/niri"
POSITION_FILE="$CONFIG_DIR/output-positions.kdl"

# Wait for niri to be ready
for i in $(seq 1 30); do
    niri msg outputs &>/dev/null && break
    sleep 1
done
sleep 1 # Let outputs settle after niri is up

# Get current output state
outputs_json=$(niri msg -j outputs 2>/dev/null) || exit 0

# Find external monitors (everything except eDP-*)
externals=$(echo "$outputs_json" \
    | jq '[to_entries[] | select(.key | startswith("eDP-") | not) | .value.logical]')

ext_count=$(echo "$externals" | jq 'length')

if [ "$ext_count" -eq 0 ]; then
    # No external monitors — remove the include so eDP-1 uses default positioning
    rm -f "$POSITION_FILE"
    exit 0
fi

# Calculate bounding box of all external monitors (in logical pixels)
bottom_y=$(echo "$externals" | jq '[.[].y + .[].height] | max')
left_x=$(echo "$externals" | jq '[.[].x] | min')
right_x=$(echo "$externals" | jq '[.[].x + .[].width] | max')

total_width=$((right_x - left_x))

# Get eDP-1 logical width
edp_width=$(echo "$outputs_json" | jq '.["eDP-1"].logical.width // 1920')

# Center eDP-1 horizontally below all external monitors
center_x=$((left_x + (total_width - edp_width) / 2))

# Only write if content changed (avoids unnecessary reloads)
new_content="// Auto-generated by arrange-outputs.sh — DO NOT EDIT
output \"eDP-1\" {
    position x=${center_x} y=${bottom_y}
}
"

if [ -f "$POSITION_FILE" ]; then
    old_content=$(cat "$POSITION_FILE")
    if [ "$old_content" = "$new_content" ]; then
        exit 0
    fi
fi

echo "$new_content" > "$POSITION_FILE"
