#!/bin/bash
# arrange-outputs.sh — Center eDP-1 below external monitor(s), and center
# a single external above eDP-1.
#
# Writes ~/.config/niri/output-positions.kdl, included by config.kdl
# via an optional include. Niri live-reloads when the file changes.
#
# Triggered by spawn-at-startup in config.kdl.
# Can also be run manually after hotplugging a monitor.

set -euo pipefail

CONFIG_DIR="$HOME/.config/niri"
POSITION_FILE="$CONFIG_DIR/output-positions.kdl"

# Wait for niri to be ready
for i in $(seq 1 30); do
    niri msg outputs &>/dev/null && break
    sleep 1
done
sleep 2 # Let outputs settle after niri is up

# Get current output state
outputs_json=$(niri msg -j outputs 2>/dev/null) || exit 0

# Find external monitors (everything except eDP-*)
externals=$(echo "$outputs_json" \
    | jq '[to_entries[] | select(.key | startswith("eDP-") | not)]')

ext_count=$(echo "$externals" | jq 'length')

if [ "$ext_count" -eq 0 ]; then
    # No external monitors — remove the include so eDP-1 uses default positioning
    rm -f "$POSITION_FILE"
    exit 0
fi

# Dimensions
edp=$(echo "$outputs_json" | jq '.["eDP-1"].logical')
edp_width=$(echo "$edp" | jq '.width // 1920')
edp_height=$(echo "$edp" | jq '.height // 1200')

ext_logicals=$(echo "$externals" | jq '[.[].value.logical]')
ext_names=$(echo "$externals" | jq -r '[.[].key]')

ext_count_num=$(echo "$externals" | jq 'length')
bottom_y=$(echo "$ext_logicals" | jq '[.[].y + .[].height] | max')

# Use the widest of eDP-1 or the external bounding box as the "centering reference"
left_x=$(echo "$ext_logicals" | jq '[.[].x] | min')
right_x=$(echo "$ext_logicals" | jq '[.[].x + .[].width] | max')
total_ext_width=$((right_x - left_x))

# eDP-1: center below external bounding box
edp_x=$((left_x + (total_ext_width - edp_width) / 2))
edp_y=$bottom_y

# For a single external monitor wider than eDP-1: also offset it so it's
# centered above eDP-1.  For multiple externals, leave their config positions
# alone (they're arranged side-by-side in config.kdl).
extra=""
if [ "$ext_count_num" -eq 1 ]; then
    ext_name=$(echo "$ext_names" | jq -r '.[0]')
    ext_w=$(echo "$ext_logicals" | jq '.[0].width')

    if [ "$ext_w" -gt "$edp_width" ]; then
        # External is wider — center it above eDP-1
        offset=$(( (ext_w - edp_width) / 2 ))
        extra="output \"${ext_name}\" {
    position x=${offset} y=0
}
"
    fi
fi

new_content="// Auto-generated by arrange-outputs.sh — DO NOT EDIT
${extra}output \"eDP-1\" {
    position x=${edp_x} y=${edp_y}
}
"

# Only write if content changed (avoids unnecessary reloads)
if [ -f "$POSITION_FILE" ]; then
    old_content=$(cat "$POSITION_FILE")
    if [ "$old_content" = "$new_content" ]; then
        exit 0
    fi
fi

echo "$new_content" > "$POSITION_FILE"
