#!/usr/bin/env bash
# Fetch a Gloo project's gitignored .env.local from bee (where it's already
# correctly configured) into the local clone on the thinkpad.
#
# bee holds the canonical .env / .env.local files for each Gloo repo
# (backed by 1Password). They're gitignored, so they don't come with a clone.
#
# Usage:  ./fetch-env.sh polymer
#         ./fetch-env.sh hummingbird
set -euo pipefail

# map project name -> repo dir name on both bee and thinkpad
declare -A REPO=(
  [polymer]=360-polymer
  [hummingbird]=360-hummingbird
  [storyhub]=360-hummingbird
  [gpl]=360-gpl
)

proj="${1:-}"
[ -n "$proj" ] || { echo "usage: $0 <polymer|hummingbird|storyhub|gpl>" >&2; exit 1; }
[ -n "${REPO[$proj]:-}" ] || { echo "unknown project: $proj" >&2; exit 1; }

repo="${REPO[$proj]}"
local_dir="$HOME/Gloo/$repo"
remote="crussell@10.10.0.12"   # bee (Nebula)

[ -d "$local_dir" ] || { echo "local clone missing: $local_dir — clone it first" >&2; exit 1; }

echo "==> Fetching .env.local for $proj from bee"
scp -o IdentitiesOnly=yes "$remote:~/Gloo/$repo/.env.local" "$local_dir/.env.local"
echo "    wrote $local_dir/.env.local ($(wc -c < "$local_dir/.env.local") bytes)"

# also grab .env if it exists on bee (it's generated by the repo's setup
# script, but having bee's copy is a known-good baseline)
if ssh -o IdentitiesOnly=yes "$remote" "test -f ~/Gloo/$repo/.env"; then
  scp -o IdentitiesOnly=yes "$remote:~/Gloo/$repo/.env" "$local_dir/.env"
  echo "    wrote $local_dir/.env"
fi
