ARG FEDORA_MAJOR_VERSION=44
FROM registry.fedoraproject.org/fedora:${FEDORA_MAJOR_VERSION}

RUN dnf -y install \
      dnf-plugins-core \
      flatpak \
      dbus-x11 \
      xdg-utils \
      xdg-desktop-portal \
      xdg-desktop-portal-gtk \
      flatpak-xdg-utils \
      mesa-dri-drivers \
      mesa-vulkan-drivers \
      vulkan-loader \
      pipewire-libs \
      wireplumber \
      which \
      findutils \
      procps-ng \
      shadow-utils \
      bash \
      coreutils \
      util-linux \
      less \
      && dnf -y copr enable ryanabx/cosmic-epoch \
      && dnf -y install cosmic-desktop \
      && dnf clean all

COPY manifest.json /usr/share/desktoppak/manifest.json

CMD ["/usr/bin/bash"]
